declare module "lucide-react" {
  import { ComponentType, SVGProps } from "react";
  export const BookOpen: ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;
  export const Code: ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;
  export const Code2: ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;
  export const FlaskConical: ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;
  export const Home: ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;
  export const Menu: ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;
  export const X: ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;
  export const Play: ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;
  export const Loader2: ComponentType<SVGProps<SVGSVGElement> & { size?: number; className?: string }>;
  export const RotateCcw: ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;
  export const Copy: ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;
  export const Check: ComponentType<SVGProps<SVGSVGElement> & { size?: number; className?: string }>;
  export const ChevronLeft: ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;
  export const ChevronRight: ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;
  export const ChevronDown: ComponentType<SVGProps<SVGSVGElement> & { size?: number; className?: string }>;
  export const CheckCircle2: ComponentType<SVGProps<SVGSVGElement> & { size?: number; className?: string }>;
  export const XCircle: ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;
  export const ArrowRight: ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;
  export const Trophy: ComponentType<SVGProps<SVGSVGElement> & { size?: number; className?: string }>;
  export const Target: ComponentType<SVGProps<SVGSVGElement> & { size?: number; className?: string }>;
  export const Shuffle: ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;
  export const TrendingUp: ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;
  export const Rocket: ComponentType<SVGProps<SVGSVGElement> & { size?: number; className?: string }>;
  export const Type: ComponentType<SVGProps<SVGSVGElement> & { size?: number; className?: string }>;
  export const Calculator: ComponentType<SVGProps<SVGSVGElement> & { size?: number; className?: string }>;
  export const GitBranch: ComponentType<SVGProps<SVGSVGElement> & { size?: number; className?: string }>;
  export const List: ComponentType<SVGProps<SVGSVGElement> & { size?: number; className?: string }>;
  export const FunctionSquare: ComponentType<SVGProps<SVGSVGElement> & { size?: number; className?: string }>;
  export const Box: ComponentType<SVGProps<SVGSVGElement> & { size?: number; className?: string }>;
  export const AlertTriangle: ComponentType<SVGProps<SVGSVGElement> & { size?: number; className?: string }>;
  export const FileText: ComponentType<SVGProps<SVGSVGElement> & { size?: number; className?: string }>;
  export const Puzzle: ComponentType<SVGProps<SVGSVGElement> & { size?: number; className?: string }>;
  export const Search: ComponentType<SVGProps<SVGSVGElement> & { size?: number; className?: string }>;
  export const Lightbulb: ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;
  export const Zap: ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;
  export const Eye: ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;
  export const EyeOff: ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;
  export const HelpCircle: ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;
  export const CornerDownLeft: ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;
  export const Bot: ComponentType<SVGProps<SVGSVGElement> & { size?: number; className?: string }>;
  export const Sparkles: ComponentType<SVGProps<SVGSVGElement> & { size?: number; className?: string }>;
  export const Quote: ComponentType<SVGProps<SVGSVGElement> & { size?: number; className?: string }>;
  export const ListChecks: ComponentType<SVGProps<SVGSVGElement> & { size?: number; className?: string }>;
}
